name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on : windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses:  actions/cache/save@v4
        with: 
          key: ${{ github.run_id }}
          path: dist
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with: 
          key: ${{ github.run_id }}
          path: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IO_TUE }}'
          channelId: live
          projectId: io-vue
